import { CatalogFeatureFilter } from "@mediaurl/sdk";

export const IptvLanguages: CatalogFeatureFilter = {
  id: "language",
  name: "Language",
  values: [
    { key: "eng", value: "English" },
    { key: "ukr", value: "Ukrainian" },
    { key: "bul", value: "Bulgarian" },
    { key: "spa", value: "Spanish" },
    { key: "ita", value: "Italian" },
    { key: "rus", value: "Russian" },
    { key: "hun", value: "Hungarian" },
    { key: "kat", value: "Georgian" },
    { key: "hye", value: "Armenian" },
    { key: "ara", value: "Arabic" },
    { key: "tur", value: "Turkish" },
    { key: "cat", value: "Catalan" },
    { key: "tam", value: "Tamil" },
    { key: "fra", value: "French" },
    { key: "deu", value: "German" },
    { key: "kur", value: "Kurdish" },
    { key: "fas", value: "Persian" },
    { key: "hin", value: "Hindi" },
    { key: "urd", value: "Urdu" },
    { key: "mal", value: "Malayalam" },
    { key: "zho", value: "Chinese" },
    { key: "yue", value: "Yue Chinese" },
    { key: "ron", value: "Romanian" },
    { key: "sqi", value: "Albanian" },
    { key: "ell", value: "Modern Greek (1453-)" },
    { key: "amh", value: "Amharic" },
    { key: "swe", value: "Swedish" },
    { key: "por", value: "Portuguese" },
    { key: "bos", value: "Bosnian" },
    { key: "srp", value: "Serbian" },
    { key: "hrv", value: "Croatian" },
    { key: "cnr", value: "Montenegrin" },
    { key: "tha", value: "Thai" },
    { key: "tuk", value: "Turkmen" },
    { key: "jpn", value: "Japanese" },
    { key: "ind", value: "Indonesian" },
    { key: "vie", value: "Vietnamese" },
    { key: "aze", value: "Azerbaijani" },
    { key: "pus", value: "Pushto" },
    { key: "kor", value: "Korean" },
    { key: "msa", value: "Malay (macrolanguage)" },
    { key: "kaz", value: "Kazakh" },
    { key: "nld", value: "Dutch" },
    { key: "khm", value: "Khmer" },
    { key: "tgl", value: "Tagalog" },
    { key: "uzb", value: "Uzbek" },
    { key: "slk", value: "Slovak" },
    { key: "cmn", value: "Mandarin Chinese" },
    { key: "heb", value: "Hebrew" },
    { key: "ltz", value: "Luxembourgish" },
    { key: "mya", value: "Burmese" },
    { key: "ben", value: "Bengali" },
    { key: "lav", value: "Latvian" },
    { key: "pol", value: "Polish" },
    { key: "ces", value: "Czech" },
    { key: "est", value: "Estonian" },
    { key: "nob", value: "Norwegian Bokmål" },
    { key: "nan", value: "Min Nan Chinese" },
    { key: "sin", value: "Sinhala" },
    { key: "som", value: "Somali" },
    { key: "dan", value: "Danish" },
    { key: "nep", value: "Nepali (macrolanguage)" },
    { key: "aii", value: "Assyrian Neo-Aramaic" },
    { key: "kin", value: "Kinyarwanda" },
    { key: "mkd", value: "Macedonian" },
    { key: "lit", value: "Lithuanian" },
    { key: "fao", value: "Faroese" },
    { key: "lao", value: "Lao" },
    { key: "slv", value: "Slovenian" },
    { key: "mri", value: "Maori" },
    { key: "fry", value: "Western Frisian" },
    { key: "pan", value: "Panjabi" },
    { key: "aka", value: "Akan" },
    { key: "isl", value: "Icelandic" },
    { key: "fin", value: "Finnish" },
    { key: "glg", value: "Galician" },
    { key: "jav", value: "Javanese" },
    { key: "iku", value: "Inuktitut" },
    { key: "bak", value: "Bashkir" },
    { key: "mon", value: "Mongolian" },
    { key: "kan", value: "Kannada" },
  ],
};

export const IptvCountries: CatalogFeatureFilter = {
  id: "country",
  name: "Country",
  values: [
    { value: "Afghanistan", key: "af" },
    { value: "Åland Islands", key: "ax" },
    { value: "Albania", key: "al" },
    { value: "Algeria", key: "dz" },
    { value: "American Samoa", key: "as" },
    { value: "Andorra", key: "ad" },
    { value: "Angola", key: "ao" },
    { value: "Anguilla", key: "ai" },
    { value: "Antigua & Barbuda", key: "ag" },
    { value: "Argentina", key: "ar" },
    { value: "Armenia", key: "am" },
    { value: "Aruba", key: "aw" },
    { value: "Australia", key: "au" },
    { value: "Austria", key: "at" },
    { value: "Azerbaijan", key: "az" },
    { value: "Bahamas", key: "bs" },
    { value: "Bahrain", key: "bh" },
    { value: "Bangladesh", key: "bd" },
    { value: "Barbados", key: "bb" },
    { value: "Belarus", key: "by" },
    { value: "Belgium", key: "be" },
    { value: "Belize", key: "bz" },
    { value: "Benin", key: "bj" },
    { value: "Bermuda", key: "bm" },
    { value: "Bhutan", key: "bt" },
    { value: "Bolivia", key: "bo" },
    { value: "Bosnia", key: "ba" },
    { value: "Botswana", key: "bw" },
    { value: "Brazil", key: "br" },
    { value: "British Virgin Islands", key: "vg" },
    { value: "Brunei", key: "bn" },
    { value: "Bulgaria", key: "bg" },
    { value: "Burkina Faso", key: "bf" },
    { value: "Burundi", key: "bi" },
    { value: "Cambodia", key: "kh" },
    { value: "Cameroon", key: "cm" },
    { value: "Canada", key: "ca" },
    { value: "Cape Verde", key: "cv" },
    { value: "Cayman Islands", key: "ky" },
    { value: "Central African Republic", key: "cf" },
    { value: "Chad", key: "td" },
    { value: "Chile", key: "cl" },
    { value: "China", key: "cn" },
    { value: "Colombia", key: "co" },
    { value: "Comoros", key: "km" },
    { value: "Congo - Brazzaville", key: "cg" },
    { value: "Congo - Kinshasa", key: "cd" },
    { value: "Cook Islands", key: "ck" },
    { value: "Costa Rica", key: "cr" },
    { value: "Côte d’Ivoire", key: "ci" },
    { value: "Croatia", key: "hr" },
    { value: "Cuba", key: "cu" },
    { value: "Curaçao", key: "cw" },
    { value: "Cyprus", key: "cy" },
    { value: "Czechia", key: "cz" },
    { value: "Denmark", key: "dk" },
    { value: "Djibouti", key: "dj" },
    { value: "Dominica", key: "dm" },
    { value: "Dominican Republic", key: "do" },
    { value: "Ecuador", key: "ec" },
    { value: "Egypt", key: "eg" },
    { value: "El Salvador", key: "sv" },
    { value: "Equatorial Guinea", key: "gq" },
    { value: "Eritrea", key: "er" },
    { value: "Estonia", key: "ee" },
    { value: "Eswatini", key: "sz" },
    { value: "Ethiopia", key: "et" },
    { value: "Faroe Islands", key: "fo" },
    { value: "Fiji", key: "fj" },
    { value: "Finland", key: "fi" },
    { value: "France", key: "fr" },
    { value: "French Guiana", key: "gf" },
    { value: "French Polynesia", key: "pf" },
    { value: "French Southern Territories", key: "tf" },
    { value: "Gabon", key: "ga" },
    { value: "Gambia", key: "gm" },
    { value: "Georgia", key: "ge" },
    { value: "Germany", key: "de" },
    { value: "Ghana", key: "gh" },
    { value: "Greece", key: "gr" },
    { value: "Greenland", key: "gl" },
    { value: "Grenada", key: "gd" },
    { value: "Guadeloupe", key: "gp" },
    { value: "Guam", key: "gu" },
    { value: "Guatemala", key: "gt" },
    { value: "Guinea", key: "gn" },
    { value: "Guinea-Bissau", key: "gw" },
    { value: "Haiti", key: "ht" },
    { value: "Honduras", key: "hn" },
    { value: "Hong Kong", key: "hk" },
    { value: "Hungary", key: "hu" },
    { value: "Iceland", key: "is" },
    { value: "India", key: "in" },
    { value: "Indonesia", key: "id" },
    { value: "International", key: "int" },
    { value: "Iran", key: "ir" },
    { value: "Iraq", key: "iq" },
    { value: "Ireland", key: "ie" },
    { value: "Israel", key: "il" },
    { value: "Italy", key: "it" },
    { value: "Jamaica", key: "jm" },
    { value: "Japan", key: "jp" },
    { value: "Jordan", key: "jo" },
    { value: "Kazakhstan", key: "kz" },
    { value: "Kenya", key: "ke" },
    { value: "Kiribati", key: "ki" },
    { value: "Kosovo", key: "xk" },
    { value: "Kuwait", key: "kw" },
    { value: "Kyrgyzstan", key: "kg" },
    { value: "Laos", key: "la" },
    { value: "Latvia", key: "lv" },
    { value: "Lebanon", key: "lb" },
    { value: "Lesotho", key: "ls" },
    { value: "Liberia", key: "lr" },
    { value: "Libya", key: "ly" },
    { value: "Liechtenstein", key: "li" },
    { value: "Lithuania", key: "lt" },
    { value: "Luxembourg", key: "lu" },
    { value: "Macao", key: "mo" },
    { value: "Madagascar", key: "mg" },
    { value: "Malawi", key: "mw" },
    { value: "Malaysia", key: "my" },
    { value: "Maldives", key: "mv" },
    { value: "Mali", key: "ml" },
    { value: "Malta", key: "mt" },
    { value: "Marshall Islands", key: "mh" },
    { value: "Martinique", key: "mq" },
    { value: "Mauritania", key: "mr" },
    { value: "Mauritius", key: "mu" },
    { value: "Mayotte", key: "yt" },
    { value: "Mexico", key: "mx" },
    { value: "Micronesia", key: "fm" },
    { value: "Moldova", key: "md" },
    { value: "Monaco", key: "mc" },
    { value: "Mongolia", key: "mn" },
    { value: "Montenegro", key: "me" },
    { value: "Montserrat", key: "ms" },
    { value: "Morocco", key: "ma" },
    { value: "Mozambique", key: "mz" },
    { value: "Myanmar", key: "mm" },
    { value: "Namibia", key: "na" },
    { value: "Nauru", key: "nr" },
    { value: "Nepal", key: "np" },
    { value: "Netherlands", key: "nl" },
    { value: "New Caledonia", key: "nc" },
    { value: "New Zealand", key: "nz" },
    { value: "Nicaragua", key: "ni" },
    { value: "Niger", key: "ne" },
    { value: "Nigeria", key: "ng" },
    { value: "Niue", key: "nu" },
    { value: "Norfolk Island", key: "nf" },
    { value: "North Korea", key: "kp" },
    { value: "North Macedonia", key: "mk" },
    { value: "Northern Mariana Islands", key: "mp" },
    { value: "Norway", key: "no" },
    { value: "Oman", key: "om" },
    { value: "Pakistan", key: "pk" },
    { value: "Palau", key: "pw" },
    { value: "Palestine", key: "ps" },
    { value: "Panama", key: "pa" },
    { value: "Papua New Guinea", key: "pg" },
    { value: "Paraguay", key: "py" },
    { value: "Peru", key: "pe" },
    { value: "Philippines", key: "ph" },
    { value: "Pitcairn Islands", key: "pn" },
    { value: "Poland", key: "pl" },
    { value: "Portugal", key: "pt" },
    { value: "Puerto Rico", key: "pr" },
    { value: "Qatar", key: "qa" },
    { value: "Réunion", key: "re" },
    { value: "Romania", key: "ro" },
    { value: "Russia", key: "ru" },
    { value: "Rwanda", key: "rw" },
    { value: "Samoa", key: "ws" },
    { value: "San Marino", key: "sm" },
    { value: "São Tomé & Príncipe", key: "st" },
    { value: "Saudi Arabia", key: "sa" },
    { value: "Senegal", key: "sn" },
    { value: "Serbia", key: "rs" },
    { value: "Seychelles", key: "sc" },
    { value: "Sierra Leone", key: "sl" },
    { value: "Singapore", key: "sg" },
    { value: "Sint Maarten", key: "sx" },
    { value: "Slovakia", key: "sk" },
    { value: "Slovenia", key: "si" },
    { value: "Solomon Islands", key: "sb" },
    { value: "Somalia", key: "so" },
    { value: "South Africa", key: "za" },
    { value: "South Korea", key: "kr" },
    { value: "South Sudan", key: "ss" },
    { value: "Spain", key: "es" },
    { value: "Sri Lanka", key: "lk" },
    { value: "St. Barthélemy", key: "bl" },
    { value: "St. Helena", key: "sh" },
    { value: "St. Kitts & Nevis", key: "kn" },
    { value: "St. Lucia", key: "lc" },
    { value: "St. Martin", key: "mf" },
    { value: "St. Pierre & Miquelon", key: "pm" },
    { value: "St. Vincent & Grenadines", key: "vc" },
    { value: "Sudan", key: "sd" },
    { value: "Sweden", key: "se" },
    { value: "Switzerland", key: "ch" },
    { value: "Syria", key: "sy" },
    { value: "Taiwan", key: "tw" },
    { value: "Tajikistan", key: "tj" },
    { value: "Tanzania", key: "tz" },
    { value: "Thailand", key: "th" },
    { value: "Timor-Leste", key: "tl" },
    { value: "Togo", key: "tg" },
    { value: "Tokelau", key: "tk" },
    { value: "Tonga", key: "to" },
    { value: "Trinidad & Tobago", key: "tt" },
    { value: "Tunisia", key: "tn" },
    { value: "Turkey", key: "tr" },
    { value: "Turkmenistan", key: "tm" },
    { value: "Turks & Caicos Islands", key: "tc" },
    { value: "Tuvalu", key: "tv" },
    { value: "U.S. Virgin Islands", key: "vi" },
    { value: "Uganda", key: "ug" },
    { value: "Ukraine", key: "ua" },
    { value: "United Arab Emirates", key: "ae" },
    { value: "United Kingdom", key: "uk" },
    { value: "United States", key: "us" },
    { value: "Uruguay", key: "uy" },
    { value: "Uzbekistan", key: "uz" },
    { value: "Vanuatu", key: "vu" },
    { value: "Vatican City", key: "va" },
    { value: "Venezuela", key: "ve" },
    { value: "Vietnam", key: "vn" },
    { value: "Wallis & Futuna", key: "wf" },
    { value: "Western Sahara", key: "eh" },
    { value: "Yemen", key: "ye" },
    { value: "Zambia", key: "zm" },
    { value: "Zimbabwe", key: "zw" },
  ],
};

export const IptvCategories: CatalogFeatureFilter = {
  id: "category",
  name: "Category",
  values: [
    { value: "Movies", key: "Movies" },
    { value: "Unsorted", key: "Unsorted" },
    { value: "Auto", key: "Auto" },
    { value: "News", key: "News" },
    { value: "Music", key: "Music" },
    { value: "General", key: "General" },
    { value: "Local", key: "Local" },
    { value: "Entertainment", key: "Entertainment" },
    { value: "Hobby", key: "Hobby" },
    { value: "Business", key: "Business" },
    { value: "Religious", key: "Religious" },
    { value: "XXX", key: "XXX" },
    { value: "Sport", key: "Sport" },
    { value: "Comedy", key: "Comedy" },
    { value: "Kids", key: "Kids" },
    { value: "Documentary", key: "Documentary" },
    { value: "Classic", key: "Classic" },
    { value: "Family", key: "Family" },
    { value: "Travel", key: "Travel" },
    { value: "Lifestyle", key: "Lifestyle" },
    { value: "Education", key: "Education" },
    { value: "Shop", key: "Shop" },
    { value: "Quiz", key: "Quiz" },
    { value: "Legislative", key: "Legislative" },
    { value: "Food", key: "Food" },
    { value: "Sci-Fi", key: "Sci-Fi" },
    { value: "Fashion", key: "Fashion" },
    { value: "Weather", key: "Weather" },
    { value: "History", key: "History" },
  ],
};
